# Generated by Django 4.1.7 on 2023-06-07 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_attendance_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name_plural': 'Оценки слушателей'},
        ),
        migrations.AlterField(
            model_name='attendance_of_classes',
            name='lesson',
            field=models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to='school.lesson', verbose_name='Курс'),
        ),
    ]
