# Generated by Django 4.1.7 on 2023-06-07 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_of_classes',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.lesson', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='attendance_of_classes',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'is_staff': False}, to=settings.AUTH_USER_MODEL, verbose_name='Посетили'),
        ),
    ]
