# Generated by Django 4.1.7 on 2023-06-08 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_attendance_of_classes_student_grade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance_of_classes',
            old_name='student_grade',
            new_name='grade',
        ),
    ]
