# Generated by Django 4.1.7 on 2023-06-08 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_teacher_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_of_classes',
            name='grade',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.attendance_of_classes', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Слушатель'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
    ]
