# Generated by Django 4.1.7 on 2023-06-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_attendance_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='grade',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Оценка'),
        ),
    ]
