# Generated by Django 4.1.7 on 2023-06-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_attendance_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(to='school.courseregistration', verbose_name='Слушатели'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_lesson',
            field=models.CharField(choices=[('1', 'Математика'), ('2', 'Физика'), ('3', 'Информатика и ИКТ')], max_length=255, verbose_name='Ведет предмет'),
        ),
    ]
