# Generated by Django 4.1.7 on 2023-06-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_alter_lesson_students_alter_teacher_teacher_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_of_classes',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'is_staff': False}, to='school.courseregistration', verbose_name='Слушатели'),
        ),
    ]
