# Generated by Django 4.1.7 on 2023-06-10 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_alter_attendance_of_classes_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.courseregistration', verbose_name='Слушатель'),
        ),
        migrations.AlterField(
            model_name='attendance_of_classes',
            name='students',
            field=models.ManyToManyField(to='school.courseregistration', verbose_name='Слушатели'),
        ),
    ]
