# Generated by Django 4.1.7 on 2023-06-10 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_alter_attendance_grade_alter_attendance_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='grade',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(blank=True, limit_choices_to={'id__in': ({'id': 3},)}, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.courseregistration', verbose_name='Слушатель'),
        ),
    ]
